# Use a PHP base image for testing
FROM php:7.4-cli

# Install necessary PHP extensions, Composer, and Codeception
RUN apt-get update && \
    apt-get install -y unzip git curl zip libpng-dev && \
    docker-php-ext-install pdo pdo_mysql && \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Install Codeception globally
RUN composer global require "codeception/codeception" --prefer-dist

# Make global composer binaries available
ENV PATH="$PATH:/root/.composer/vendor/bin"
